export const LOGIN_SUCCESS =  'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_START = 'LOGIN_START'
export const LOG_OUT = 'LOG_OUT'
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH"

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAILED = "SIGN_UP_FAILED"
export const SIGN_UP_START = "SIGN_UPSTARTS"


export const OTP_SUCCESS = "OTP_SUCCESS"
export const OTP_FAILED = "OTP_FAILED"
export const OTP_START = "OTP_START"


export const START_PRODUCTS = "START_PRODUCTS"
export const SUCCESS_PRODUCTS = "SUCCESS_PRODUCTS"
export const FAILED_PRODUCTS = "FAILED_PRODUCTS"


export const START_PRODUCT = "START_PRODUCT"
export const SUCCESS_PRODUCT = "SUCCESS_PRODUCT"
export const FAILED_PRODUCT = "FAILED_PRODUCT"


export const START_INVENTORY = "START_INVENTORY"
export const SUCCESS_INVENTORY = "SUCCESS_INVENTORY"
export const FAILED_INVENTORY = "FAILED_INVENTORY"


export const START_GET_CART = "START_GET_CART"
export const SUCCESS_GET_CART = "SUCCESS_GET_CART"
export const FAILED_GET_CART = "FAILED_GET_CART"


export const START_REMOVE_CART = "START_REMOVE_CART"
export const SUCCESS_REMOVE_CART = "SUCCESS_REMOVE_CART"
export const FAILED_REMOVE_CART = "FAILED_REMOVE_CART"


export const START_ADD_CART = "START_ADD_CART"
export const SUCCESS_ADD_CART = "SUCCESS_ADD_CART"
export const FAILED_ADD_CART = "FAILED_ADD_CART"

export const START_UPDATE_CART = "START_UPDATE_CART"
export const SUCCESS_UPDATE_CART = "SUCCESS_UPDATE_CART"
export const FAILED_UPDATE_CART = "FAILED_UPDATE_CART"